config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles
  resources :resumes
  resources :abouts
  resources :services
  resources :contacts , only:[:new, :create]
  root 'welcome#index'
  get '*path' => redirect('/')
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged
    
    before_validation { avatar.clear if @delete_avatar }
    has_attached_file :avatar, 
        :styles => { :medium => "300x300>", :thumb => "100x100>" }, 
        :default_url => "missing.png",
        :storage => :dropbox,
        :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
        :dropbox_options => {
            :path => proc { |style| "#{style}/#{id}_#{avatar.original_filename}"},
            :unique_filename => true
        }
    #validates :avatar, :attachment_presence => true
    # Validate content type
    validates_attachment_content_type :avatar, :content_type => /\Aimage/
    # Validate filename
    validates_attachment_file_name :avatar, :matches => [/png\Z/, /jpe?g\Z/]

    def delete_avatar
        @delete_avatar ||= false
    end

    def delete_avatar=(value)
        if value
        self.avatar = nil
        end
        @delete_avatar  = !value.to_i.zero?
    end
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :subject_contact, :validate => true
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true


	 def headers
	  	{
		  	:subject => "#{subject_contact}",
		  	:to => "araujoadvocacia.jur@gmail.com",
		  	:from => %("#{name}" <#{email}>)
		  }
    end

end

app/models/post.rb
class Post < ApplicationRecord

  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/resume.rb
class Resume < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged

    before_validation { avatar.clear if @delete_avatar }
    has_attached_file :avatar, 
        :styles => { :medium => "300x300>", :thumb => "100x100>" }, 
        :default_url => "missing.png",
        :storage => :dropbox,
        :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
        :dropbox_options => {
        :path => proc { |style| "#{style}/#{id}_#{avatar.original_filename}"},
        :unique_filename => true
        }
    #validates :avatar, :attachment_presence => true
    # Validate content type
    validates_attachment_content_type :avatar, :content_type => /\Aimage/
    # Validate filename
    validates_attachment_file_name :avatar, :matches => [/png\Z/, /jpe?g\Z/]

    def delete_avatar
        @delete_avatar ||= false
    end

    def delete_avatar=(value)
        if value
        self.avatar = nil
        end
        @delete_avatar  = !value.to_i.zero?
    end
end

app/models/service.rb
class Service < ApplicationRecord

     extend FriendlyId
     friendly_id :title, use: :slugged

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  # :recoverable, :rememberable, :trackable, :validatable


   devise :database_authenticatable,:recoverable,
	 :rememberable, :trackable, :validatable





end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController

    before_action :find_about, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except:[:index, :show]



    def index
        @abouts = About.all.order("created_at DESC")
    end

    def new
        @about = About.new
    end


    def create
        @about = About.new(about_params)
        if @about.save
            redirect_to @about
        else
            render 'new'
        end
    end

    def show
    end

    def edit
    end

    def update
        if @about.update(about_params)
            redirect_to @about
        else
            render 'edit'
        end
    end

    def destroy
        @about.destroy
        redirect_to root_path
    end

    private

    def find_about
        @about = About.friendly.find(params[:id])
    end

    def about_params
        params.require(:about).permit(:title, :body, :slug)
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:index, :show]


  def index
      @articles = Article.all.order("created_at DESC").paginate(page:params[:page], per_page: 3)

      @other_articles = Article.all.order("created_at ASC")

  end
  

  def new
    @article = Article.new
  end


  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def show
    @other_articles = Article.all.order("created_at ASC")
  end

  def edit
  end


  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path
  end

  private

  def find_article
    @article = Article.friendly.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :slug,:name_author, :description_author, :avatar)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = 'Não foi possivel enviar a mensagem'
			render :new
		end
	end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
    before_action :find_resume, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except:[:index, :show]

    def index
        @resumes = Resume.all.order("created_at DESC").paginate(page:params[:page], per_page: 3)
    end

    def new
        @resume = Resume.new
    end

    def create
        @resume = Resume.new(resume_params)
        if @resume.save
            redirect_to @resume
        else
            render 'new'
        end
    end

    def show
    end

    def edit
    end

    def update
        if @resume.update(resume_params)
            redirect_to @resume
        else
            render 'edit'
        end
    end

    def destroy
        @resume.destroy
        redirect_to root_path
    end


    private

    def find_resume
        @resume = Resume.friendly.find(params[:id])
    end

    def resume_params
        params.require(:resume).permit(:title,:body, :slug, :avatar)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

    before_action :find_service, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except:[:index, :show]

    def index
        @services = Service.all.order("created_at  DESC")

        @other_services  =  Service.all.order("created_at ASC")
    end

    def new
        @service = Service.new
    end

    def create
        @service = Service.new(service_params)
        if @service.save
            redirect_to @service
        else
            render 'new'
        end

    end

    def show
    end

    def edit
    end


    def update
        if @service.update(service_params)
            redirect_to @service
        else
            render 'edit'
        end
    end


    def destroy
        @service.destroy
        redirect_to root_path
    end

    private

    def find_service
        @service = Service.friendly.find(params[:id])
    end

    def service_params
        params.require(:service).permit(:title, :body, :slug)
    end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  
  def index
    @services = Service.all.order("created_at DESC").limit(3)
  end

  
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
    <%= form_for @article do |f| %>
        <div class="field">
        <%= f.label :avatar %>
        <%= f.file_field :avatar%>
        </div>
        <%= f.label :title, 'Título'%><br>
        <%= f.text_field :title%> <br>
        <br>
        <%= f.cktext_area :body, rows: 10 %>
        <br>    
        <%= f.label :name_author, 'Autor:'%><br>
        <%= f.text_field :name_author%> <br>
        <br>
        <%= f.label :description_author, 'Sobre o Autor:'%><br>
        <%= f.cktext_area :description_author%> <br>
        <br>
        <%= f.submit "Publicar", class: "btn" %>
    <% end %>
    <br>
</div>

app/views/articles/edit.html.erb
<div class="container">
<h1>Editar Artigo</h1>

<%= render 'form'%>

app/views/articles/index.html.erb
<div class="section">
 
  <div class="row">
   

    <div class="col s12 m7 card">
        <% @articles.each do |article| %>
            <div class="card-content">
                <h4 class="gray-text"><%=article.title%></h4>
                <p class="gray-text"><%= truncate(article.body, :length => 300 , :escape => false) %></p>
            </div>
            <div class="card-action">
                <p class="date"><%= article.created_at.strftime("%b %d, %Y")%></p>

                <%= link_to "Mais", article, class:"waves-effect waves-light brown  btn"%>
            </div>
        <% end %>

        <%= will_paginate @articles %>
    </div>


   <div class="col s12 m4 card board-article">
      <h4 class="center black-text">Outros artigos</h4>
      <hr>
        <% @other_articles.each do |o| %>
            <ul>
                <i class="fa fa-bookmark-o" aria-hidden="true"></i>  <%= link_to o.title, o %>
            </ul>
        <%end%>
   </div>
    

   <div>
    
   </div>

  </div>


</div>

app/views/articles/new.html.erb
<div class="container">

<h1>Novo Artigo</h1>

<%= render 'form'%>

app/views/articles/show.html.erb
<div class="section">
 
  <div class="row">
   

    <div class="col s12 m7">
      
      <h4><%= @article.title%></h4>
      <hr>
      <div><%= @article.body.html_safe%></div>
      <hr>

      <div class="col s12 m12">
          <div class="row valign-wrapper">
            <div class="col s2">
              <%= image_tag @article.avatar.url(:thumb), class:' circle responsive-image' %>
            </div>
            <div class="col s10 offset-l1">
              <span class="black-text">
                <%= @article.description_author.html_safe%></h1>.
              </span>
            </div>
          </div>
      </div>
      <hr>  

      <% if user_signed_in? %>
        <%= link_to "Edit article", edit_article_path(@article) %> |
        <%= link_to "Delete article", article_path(@article), method: :delete, data:{confirm: "Are you sure?"} %>
      <% end %>

    

    </div>


   <div class="col s12 m4 card board-article">
      <h4 class="center black-text">Outros artigos</h4>
      <hr>
        <% @other_articles.each do |o| %>
            <ul>
                <i class="fa fa-bookmark-o" aria-hidden="true"></i>  <%= link_to o.title, o %>
            </ul>
        <%end%>
   </div>
    

   <div>
    
   </div>

  </div>


</div>

app/views/contacts/create.html.erb
<div class="container">
  <h1>Obrigado pela sua mensagem</h1>
  <p>
    Entraremos em contato em breve.
  </p>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>

</div>

app/views/contacts/new.html.erb
<div class="container">
  <br>
  <h1 class="center grey-text">Contato</h1>
  <hr>
  <div class="row">
  
<div class="col s12 m6 card">
<%= form_for @contact do |f|  %>

 <div class="input-field col s12 m6">
   <%= f.label :name,'Nome'%>
   <%= f.text_field :name, required:true, class:'validate'%>
 </div>


 <div class="input-field col s12 m6">
   <%= f.label :email, 'Email'%>
   <%= f.email_field :email, required:true, class:'validate'%>
 </div>

 <div class="row">
   <div class="input-field col s12 m12">
     <%= f.label :subject_contact, 'Assunto'%>
     <%= f.text_field :subject_contact, required:true, class:'validate'%>
   </div>
 </div>

 <div class="row">
   <div class="input-field col s12 m12">
     <%= f.label :message, 'Mensagem'%><br>
     <%= f.text_area :message, class:'materialize-textarea'%><br>
   </div>
 </div>


 <div class="row center">
       <%= f.submit 'Enviar', class: 'waves-effect waves-light grey btn' %><br>
 </div>
 <% end %>
</div>

   <div class="col s12 m6 down-position">
    <script src='https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyB8ubbieOefDKCEtT-0-hxU7sTJaaiAS_0'></script><div style='overflow:hidden;height:410px;width:100%;'><div id='gmap_canvas' style='height:400px;width:520px;margin-top:10px;'></div><style>#gmap_canvas img{max-width:none!important;background:none!important}</style></div> <a href='http://maps-generator.com/pt'>Maps-Generator</a> <script type='text/javascript' src='https://embedmaps.com/google-maps-authorization/script.js?id=dd6a0bff752bd5c9f4801a83a6a3944c018f3f0d'></script><script type='text/javascript'>function init_map(){var myOptions = {zoom:12,center:new google.maps.LatLng(-16.6930489,-49.25901590000001),mapTypeId: google.maps.MapTypeId.ROADMAP};map = new google.maps.Map(document.getElementById('gmap_canvas'), myOptions);marker = new google.maps.Marker({map: map,position: new google.maps.LatLng(-16.6930489,-49.25901590000001)});infowindow = new google.maps.InfoWindow({content:'<strong>Araújo Advocacia e Consultoria.</strong><br>Rua 132, Nº 300 | Setor Sul<br> 74093-210 Goiânia<br>'});google.maps.event.addListener(marker, 'click', function(){infowindow.open(map,marker);});infowindow.open(map,marker);}google.maps.event.addDomListener(window, 'load', init_map);</script>
   </div>
  </div>


</div>

app/views/resumes/_form.html.erb
    <%= form_for @resume do |f| %>
        <div class="field">
            <%= f.label :avatar %>
            <%= f.file_field :avatar%>
        </div>
        <%= f.label :title, 'Nome'%><br>
        <%= f.text_field :title%> <br>
        <br>
        <%= f.cktext_area :body, rows: 10 %>
        <br>
         <%= f.submit "Publicar", class: "btn" %>
        
    <% end %>
    <br>
</div>

app/views/resumes/edit.html.erb
<div class="container">
<h1>Editar Curriculo</h1>

<%= render 'form'%>

app/views/resumes/index.html.erb
<div class="section">
    <div class="row ">
        <% @resumes.each do |resume| %>
         <div class="col s12 m6">
        <div class="card-panel grey lighten-5 z-depth-1">
          <div class="row valign-wrapper">
            <div class="col s2 m2">
              <%= image_tag resume.avatar.url(:thumb), class:"circle responsive-image" %>
            </div>
            <div class="col s10 m8">
                <span class="black-text">
                    <h5 class="gray-text"><%=resume.title%></h5>
                </span>
                <hr>

                <%= link_to "Sobre...", resume, class:"waves-effect waves-light grey  lighten-1  btn"%>
            </div>
          </div>
        </div>
      </div>

    <% end %>
   
    </div>
         <br>
        <br>
        <br>
        <br>
        <br>
</div>

app/views/resumes/new.html.erb
<div class="container">
<h1>Novo Curriculo</h1>

<%= render 'form'%>

app/views/resumes/show.html.erb
<div class="section">
  <div class="container">
    <div class="row">
      <%= image_tag @resume.avatar.url(:thumb), class:' circle responsive-image' %>
      <h4><%= @resume.title%></h4>
      <hr>
      <div><%= @resume.body.html_safe%></div>
      <hr>

      <% if user_signed_in? %>
        <%= link_to "Edit resume", edit_resume_path(@resume) %> |
        <%= link_to "Delete resume", resume_path(@resume), method: :delete, data:{confirm: "Are you sure?"} %>
      <% end %>

    </div>
  </div>
</div>

app/views/services/_form.html.erb
    <%= form_for @service do |f| %>
        <%= f.label :title, 'Título'%><br>
        <%= f.text_field :title%> <br>
        <br>
        <%= f.cktext_area :body, rows: 10 %>
        <br>
         <%= f.submit "Publicar", class: "btn" %>
       
    <% end %>
    <br>
</div>

app/views/services/edit.html.erb
<div class="container">
<h1>Editar o Serviço</h1>

<%= render 'form'%>

app/views/services/index.html.erb
<div class="section no-pad-bot" id="index-banner">
  <div class="container">
    <h3 class="header center grey-text">Nossos serviços para lhe atender</h3>
    <hr>    
  </div>
  <br><br>
</div>
<div class="container">

    <div class="row">
        <% @services.each do |service| %>
          <div class="col s12 m4">
              <div class="card  darken-1 z-depth-4">
              <div class="card-content black-text">
                  <span class="card-title "><%= service.title%></span>
                  <hr>
                  <p><%= truncate(service.body, :length => 300 , :escape => false) %></p>
              </div>
              <div class="card-action">
                  <%= link_to "Mais...", service, class:"black-text" %>
              </div>
              </div>
          </div>
        <% end %>
    </div>         
</div>

app/views/services/new.html.erb
<div class="container">

<h1>Novo Serviço</h1>

<%= render 'form'%>

app/views/services/show.html.erb
<div class="container">
<h1><%= @service.title%></h1>
<hr>
<div><%= @service.body.html_safe%></div>


<br>
<% if user_signed_in? %>
  <%= link_to "Edit service", edit_service_path(@service) %> |
  <%= link_to "Delete service", service_path(@service), method: :delete, data:{confirm: "Are you sure?"} %>
<% end %>
<br>
</div>