config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles
  resources :resumes
  resources :abouts
  resources :services
  resources :contacts , only:[:new, :create]
  root 'welcome#index'
  get '*path' => redirect('/')
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged
    
    before_validation { avatar.clear if @delete_avatar }
    has_attached_file :avatar, 
        :styles => { :medium => "300x300>", :thumb => "100x100>" }, 
        :default_url => "missing.png",
        :storage => :dropbox,
        :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
        :dropbox_options => {
            :path => proc { |style| "#{style}/#{id}_#{avatar.original_filename}"},
            :unique_filename => true
        }
    #validates :avatar, :attachment_presence => true
    # Validate content type
    validates_attachment_content_type :avatar, :content_type => /\Aimage/
    # Validate filename
    validates_attachment_file_name :avatar, :matches => [/png\Z/, /jpe?g\Z/]

    def delete_avatar
        @delete_avatar ||= false
    end

    def delete_avatar=(value)
        if value
        self.avatar = nil
        end
        @delete_avatar  = !value.to_i.zero?
    end
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :subject_contact, :validate => true
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true


	 def headers
	  	{
		  	:subject => "#{subject_contact}",
		  	:to => "araujoadvocacia.jur@gmail.com",
		  	:from => %("#{name}" <#{email}>)
		  }
    end

end

app/models/post.rb
class Post < ApplicationRecord

  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/resume.rb
class Resume < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged

    before_validation { avatar.clear if @delete_avatar }
    has_attached_file :avatar, 
        :styles => { :medium => "300x300>", :thumb => "100x100>" }, 
        :default_url => "missing.png",
        :storage => :dropbox,
        :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
        :dropbox_options => {
        :path => proc { |style| "#{style}/#{id}_#{avatar.original_filename}"},
        :unique_filename => true
        }
    #validates :avatar, :attachment_presence => true
    # Validate content type
    validates_attachment_content_type :avatar, :content_type => /\Aimage/
    # Validate filename
    validates_attachment_file_name :avatar, :matches => [/png\Z/, /jpe?g\Z/]

    def delete_avatar
        @delete_avatar ||= false
    end

    def delete_avatar=(value)
        if value
        self.avatar = nil
        end
        @delete_avatar  = !value.to_i.zero?
    end
end

app/models/service.rb
class Service < ApplicationRecord

     extend FriendlyId
     friendly_id :title, use: :slugged

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  # :recoverable, :rememberable, :trackable, :validatable


   devise :database_authenticatable,:recoverable,
	 :rememberable, :trackable, :validatable





end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController

    before_action :find_about, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except:[:index, :show]



    def index
        @abouts = About.all.order("created_at DESC")
    end

    def new
        @about = About.new
    end


    def create
        @about = About.new(about_params)
        if @about.save
            redirect_to @about
        else
            render 'new'
        end
    end

    def show
    end

    def edit
    end

    def update
        if @about.update(about_params)
            redirect_to @about
        else
            render 'edit'
        end
    end

    def destroy
        @about.destroy
        redirect_to root_path
    end

    private

    def find_about
        @about = About.friendly.find(params[:id])
    end

    def about_params
        params.require(:about).permit(:title, :body, :slug)
    end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
    before_action :find_resume, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except:[:index, :show]

    def index
        @resumes = Resume.all.order("created_at DESC").paginate(page:params[:page], per_page: 3)
    end

    def new
        @resume = Resume.new
    end

    def create
        @resume = Resume.new(resume_params)
        if @resume.save
            redirect_to @resume
        else
            render 'new'
        end
    end

    def show
    end

    def edit
    end

    def update
        if @resume.update(resume_params)
            redirect_to @resume
        else
            render 'edit'
        end
    end

    def destroy
        @resume.destroy
        redirect_to root_path
    end


    private

    def find_resume
        @resume = Resume.friendly.find(params[:id])
    end

    def resume_params
        params.require(:resume).permit(:title,:body, :slug, :avatar)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  
  def index
    @services = Service.all.order("created_at DESC").limit(3)
  end

  
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
  <footer class="page-footer grey darken-3">
   <a href="" class="topo"><i class="fa fa-arrow-up fa-2x"></i></a>
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Araújo</h5>
          <p class="grey-text text-lighten-4">Advocacia e Consultoria.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Endereço</h5>
          <ul>
            <li><a class="white-text" href="#!">Rua 132, Nº 300 | CEP: 74093-210| Setor Sul | Goiânia/GO</a></li>
            <li><a class="white-text" href="#!">(62) 3093-1023</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Horário de Funcionamento</h5>
          <ul>
            <li><a class="white-text" href="#!">Funcionamento: De 2ª a 6ª, das 08h às 18h</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright grey darken-4">
      <div class="container">
        Desenvolvido por - <a class="brown-text text-lighten-3" href="http://99bemore.com.br">99beMore</a>
      </div>
    </div>
  </footer>

app/views/layouts/_navbar.html.erb
<nav class="white" role="navigation">
    <div class="nav-wrapper container">
      <a href="/" class="page-scroll black-text title-logo">Araújo</a>
      <ul class="right hide-on-med-and-down">
        <li><%= link_to "Sobre", abouts_path %></li>
        <li><%= link_to "Serviços", services_path %></li>
        <li><%= link_to "Currículo", resumes_path %></li>
        <li><%= link_to "Artigos", articles_path %></li>
        <li><%= link_to "Contato",    new_contact_path, class:'black-text'%></li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><%= link_to "Sobre", abouts_path %></li>
        <li><%= link_to "Serviços", services_path %></li>
        <li><%= link_to "Currículo", resumes_path %></li>
        <li><%= link_to "Artigos", articles_path %></li>
        <li><%= link_to "Contato",    new_contact_path, class:'black-text'%></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Araújo Advocacia</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>